name: Test Jenkins Action

on:
  workflow_dispatch:


jobs:

  testaction:
    
    runs-on: ubuntu-latest
    
    steps:
      
      - id: testjenkinsaction
        uses: mickeygoussetorg/trigger-jenkins-job@v1
        with:
          jenkins-server: http://localhost:8071/
          jenkins-job: test
          jenkins-username: Test
          jenkins-pat: 1140a8ab94d3c044d99653b873c8ebc86d
          poll-time: 100
          timeout-value: 100
          verbose: true
